# Generated by Django 5.2.6 on 2025-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('desc', models.TextField(max_length=150)),
                ('tipo', models.CharField(choices=[('MADERA', 'Maderas y Trozos'), ('BARNIZ', 'Barnices y Pinturas'), ('HERRAJE', 'Herrajes y Piezas'), ('CUERDAS', 'Cuerdas'), ('HERRAMIENTA', 'Herramientas'), ('OTRO', 'Otros')], default='MADERA', max_length=20, verbose_name='Tipo de Material')),
                ('unidad', models.CharField(choices=[('KILOS', 'Kilogramo'), ('LITROS', 'Litros'), ('PIEZAS', 'Piezas'), ('TABLONES', 'Tablones'), ('LAMINAS', 'Laminas')], default='KILOS', max_length=20, verbose_name='Unidad de medida')),
            ],
        ),
    ]
