# Generated by Django 5.2.6 on 2025-11-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True, 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelTable(
            name='material',
            table='',
        ),
    ]
