# Generated by Django 5.2.6 on 2025-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_material_options_alter_material_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='desc',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
