# Generated by Django 5.2.6 on 2026-02-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_material_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la entrega'),
        ),
    ]
