# Generated by Django 5.2.6 on 2025-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nro_tlf',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
