# Generated by Django 5.2.6 on 2026-02-13 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_alter_alertastock_fecha'),
        ('usuarios', '0002_alter_customuser_nro_tlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Administrador', to='inventarios.inventarios'),
        ),
    ]
