# Generated by Django 5.2.6 on 2026-02-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_admin_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
