# Generated by Django 5.2.6 on 2025-11-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inv_escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('ubic', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stock_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inv_escuela')),
            ],
        ),
    ]
