# Generated by Django 5.2.6 on 2025-11-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_escuela',
            name='es_depo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock_inv',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material'),
        ),
    ]
