# Generated by Django 5.2.6 on 2025-11-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_inv_escuela_es_depo_alter_stock_inv_inv'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_inv',
            name='mat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiales.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_inv',
            name='mat_min_qty',
            field=models.PositiveIntegerField(default=5, verbose_name='Cantidad Minima'),
        ),
        migrations.AddField(
            model_name='stock_inv',
            name='mat_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='stock_inv',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inv_escuela'),
        ),
    ]
