# Generated by Django 5.2.6 on 2025-11-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_stock_inv_mat_stock_inv_mat_min_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('ubic', models.TextField(max_length=100)),
                ('es_depo', models.BooleanField(default=False, verbose_name='Es Depósito Central?')),
            ],
        ),
        migrations.AlterField(
            model_name='stock_inv',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventarios'),
        ),
        migrations.DeleteModel(
            name='inv_escuela',
        ),
    ]
