# Generated by Django 5.2.6 on 2025-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_inventarios_alter_stock_inv_inv_delete_inv_escuela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarios',
            options={'managed': True, 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='stock_inv',
            options={'managed': True, 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='inventarios',
            name='ubic',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='inventarios',
            table='',
        ),
        migrations.AlterModelTable(
            name='stock_inv',
            table='',
        ),
    ]
