# Generated by Django 5.2.6 on 2025-12-02 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_alter_inventarios_options_alter_stock_inv_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_inv',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='inventarios.inventarios'),
        ),
    ]
