# Generated by Django 5.2.6 on 2025-12-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_alter_stock_inv_inv'),
        ('materiales', '0003_alter_material_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_inv',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material'),
        ),
    ]
