# Generated by Django 5.2.6 on 2025-12-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_stock_inv_mat'),
        ('materiales', '0003_alter_material_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('resuelto', models.BooleanField(default=False)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventarios')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Alerta Stock',
                'verbose_name_plural': 'Alertas Stock',
            },
        ),
    ]
