# Generated by Django 5.2.6 on 2025-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_alertastock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertastock',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
