# Generated by Django 5.2.6 on 2025-12-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0005_alter_inventarios_options_alter_stock_inv_options_and_more'),
        ('materiales', '0003_alter_material_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_mov', models.FloatField(max_length=100)),
                ('fecha_Mov', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'In'), ('Salida', 'Out'), ('Ajuste', 'Adjust')], default='Entrada', max_length=20, verbose_name='Tipo de Movimiento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventarios', verbose_name='Inventario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
