# Generated by Django 5.2.6 on 2025-12-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_alter_inventarios_options_alter_stock_inv_options_and_more'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='inv_Stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.stock_inv', verbose_name='stock'),
        ),
    ]
