# Generated by Django 5.2.6 on 2025-12-02 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_alter_inventarios_options_alter_stock_inv_options_and_more'),
        ('transacciones', '0002_movimientos_inv_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='inv_Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.stock_inv', verbose_name='stock'),
        ),
    ]
