# Generated by Django 5.2.6 on 2025-12-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_stock_inv_mat'),
        ('transacciones', '0003_alter_movimientos_inv_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='inv_Stock',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='inventario',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='inv_dests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrantes', to='inventarios.inventarios', verbose_name='Enviar a (Opcional)'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='inv_orig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventarios', verbose_name='Inventario de origen'),
        ),
    ]
