# Generated by Django 5.2.6 on 2025-12-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_remove_movimientos_inv_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='inv_dests',
            new_name='inv_dest',
        ),
    ]
