# Generated by Django 5.2.6 on 2025-12-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_stock_inv_mat'),
        ('transacciones', '0005_rename_inv_dests_movimientos_inv_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='stock_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.stock_inv'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='inv_orig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movimientos', to='inventarios.inventarios', verbose_name='Inventario de origen'),
        ),
    ]
