# Generated by Django 5.2.6 on 2025-12-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_alertastock'),
        ('transacciones', '0006_movimientos_stock_afectado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='inv_orig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movimientos', to='inventarios.inventarios', verbose_name='Inventario afectado'),
        ),
    ]
